apiVersion: v1
kind: Service
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
    component: fedemeter-api
  name: fedemeter-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: fedemeter-api
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: fedemeter-api
  type: ClusterIP
