{{- if .Values.cosi.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3gw-cosi.driverSecretName" . }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DRIVERNAME: {{ include "s3gw-cosi.driverName" . }}
  ENDPOINT: {{ include "s3gw-cosi.endpoint" . }}
  ACCESSKEY: {{ .Values.accessKey }}
  SECRETKEY: {{ .Values.secretKey }}
{{- end }}
