apiVersion: v1
kind: Service
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  {{- with .Values.federatoraiRest.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
    component: federatorai-rest
  name: federatorai-rest
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.federatoraiRest.service.clusterIP }}
  clusterIP: {{ .Values.federatoraiRest.service.clusterIP }}
  {{- end }}
  ports:
  - name: restapi-http
    port: 5055
    protocol: TCP
    targetPort: 5055
  - name: restapi-https
    port: 5056
    protocol: TCP
    targetPort: 5056
  - name: restapi-burrow
    port: 5059
    protocol: TCP
    targetPort: 5059
  selector:
    component: federatorai-rest
  type: ClusterIP
