---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeslice-api-gw
  name: kubeslice-api-gw
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 3000
  selector:
    app: kubeslice-api-gw
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeslice-api-gw
  name: kubeslice-api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeslice-api-gw
  template:
    metadata:
      labels:
        app: kubeslice-api-gw
    spec:
      containers:
        - image: '{{ .Values.kubeslice.apigw.image }}:{{ .Values.kubeslice.apigw.tag }}'
          imagePullPolicy: '{{ .Values.kubeslice.apigw.pullPolicy }}'
          env:
            - name: KUBESLICE_CONTROLLER_PROMETHEUS
              value: {{ .Values.kubeslice.prometheus.url }}
          name: kubeslice-api-gw
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/secrets
              name: oidc-secrets
      {{- if and .Values.imagePullSecrets .Values.imagePullSecrets.repository .Values.imagePullSecrets.username .Values.imagePullSecrets.password }}
      imagePullSecrets:
        - name: kubeslice-ui-image-pull-secret
      {{- end }}
      restartPolicy: Always
      serviceAccount: kubeslice-api-gw
      serviceAccountName: kubeslice-api-gw
      volumes:
        - name: oidc-secrets
          secret:
            secretName: kubeslice-ui-oidc
            optional: true
