apiVersion: v1
kind: Service
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
    component: alameda-influxdb
  name: alameda-influxdb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    component: alameda-influxdb
  type: ClusterIP
