annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Percona Operator for MongoDB
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: psmdb-operator
apiVersion: v2
appVersion: 1.13.0
description: A Helm chart for Deploying the Percona Kubernetes Operator for Percona
  Server for MongoDB
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/kubernetes.html
icon: https://raw.githubusercontent.com/percona/percona-server-mongodb-operator/main/operator.png
maintainers:
- email: ivan.pylypenko@percona.com
  name: cap1984
- email: tomislav.plavcic@percona.com
  name: tplavcic
name: psmdb-operator
version: 1.13.1
