---
apiVersion: v1
clusters:
- cluster:
    server: https://localhost:9444
    insecure-skip-tls-verify: true
  name: EKS_CLUSTER_ARN
contexts:
- context:
    cluster: EKS_CLUSTER_ARN
    user: cluster/EKS_CLUSTER_NAME
  name: EKS_CLUSTER_ARN
current-context: EKS_CLUSTER_ARN
kind: Config
preferences: {}
users:
- name: cluster/EKS_CLUSTER_NAME
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - EKS_REGION
      - eks
      - get-token
      - --cluster-name
      - EKS_CLUSTER_NAME
      command: aws
      env:
      - name: AWS_ACCESS_KEY_ID
        value:  EKS_OWNER_ACCESS
      - name: AWS_SECRET_ACCESS_KEY
        value: EKS_OWNER_SECRET