apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3000"
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
  name: my-alamedaservice
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.global.imageTag }}
  imageLocation: quay.io/prophetstor
  storages:
    - type: ephemeral
      usage: data
    - type: ephemeral
      usage: log
