url: https://github.com/dell/csi-powerflex.git                                                                                                   
subdirectory: helm/csi-vxflexos                                                                                                                  
commit: 582409d6e0849f53cf9997ee426eca7ba2773c7b                                                                                                 
packageVersion: 00
