annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Pixie
  catalog.cattle.io/release-name: pixie
apiVersion: v2
name: pixie-operator-chart
type: application
version: 0.0.3401
