annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Apache Airflow
  catalog.cattle.io/kube-version: '>=1.19-0'
  catalog.cattle.io/release-name: airflow
  category: WorkFlow
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.6.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: file://./charts/redis
  version: 17.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: file://./charts/postgresql
  version: 12.x.x
- name: common
  repository: file://./charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Airflow is a tool to express and execute workflows as directed
  acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress
  and handle task dependencies.
home: https://bitnami.com
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/airflow-1.svg
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 14.2.5
