apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
  name: federatorai-operator
subjects:
- kind: ServiceAccount
  name: federatorai-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: federatorai-operator
  apiGroup: rbac.authorization.k8s.io
