apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
  name: alameda-ai-log.pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.alamedaAi.persistence.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.alamedaAi.persistence.logStorageSize }}
{{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
{{- end }}
