apiVersion: v1
kind: Service
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
    component: fedemeter-influxdb
  name: fedemeter-influxdb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-fedemeter-influxdb
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: tcp-fedemeter-influxdb
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    component: fedemeter-influxdb
  type: ClusterIP
