apiVersion: v1
data:
  config.toml: |-
    clusterName = ""

    [datahub]
    address = "alameda-datahub.{{ .Release.Namespace }}.svc"
    port = 50050

    [rest]
    rest_service_address = "federatorai-rest.{{ .Release.NameSpace }}.svc"
    rest_service_port = 5056

    [executor]
    check_cycle = 30 # second
    expire_time = 300 # second
    enable = true

    [log]
    enable_log_caller = true
    output_log_level = "info"
kind: ConfigMap
metadata:
  annotations: {{ include "render-value" ( dict "value" .Values.global.commonAnnotations "context" .) | nindent 4 }}
  labels: {{ include "render-value" ( dict "value" .Values.global.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: federatorai
    app: alameda
  name: alameda-executor-config
  namespace: {{ .Release.Namespace }}
