activitymanager:
  activitymanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.7
    imageTagArm: 4.2.6.onprem-arm64.1
alertmanager:
  alertmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.38
    imageTagArm: 4.2.6.onprem-arm64.2
appscanner:
  appscanner:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.11
    imageTagArm: 4.2.6.onprem-arm64.1
appworker:
  appworker:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: 4.2.6.onprem.9
    imageTagArm: 4.2.6.onprem-arm64.2
cloudmanager:
  cloudmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
clustermanager:
  clustermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.9
    imageTagArm: 4.2.6.onprem-arm64.1
clustertemplatemanager:
  clustertemplatemanager:
    imageTag: 4.2.6.onprem.6
    imageTagArm: 4.2.6.onprem-arm64.2
configmanager:
  configmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.6
    imageTagArm: 4.2.6.onprem-arm64.1
costmanager:
  costmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
deploymentmanager:
  deploymanager:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: 4.2.6.onprem.8
    imageTagArm: 4.2.6.onprem-arm64.1
domainmanager:
  domainmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.7
    imageTagArm: 4.2.6.onprem-arm64.1
esearch:
  esearch:
    envMap:
      discovery.type: single-node
    image: elasticsearch
    imageTag: 1.7.3
gateway:
  gateway:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
  gpkubeux:
    envMap:
      HOST: 0.0.0.0
    imageTag: 4.2.6.onprem.41
    imageTagArm: 4.2.6.onprem-arm64.1
    gpReleaseVersion: 4.2.6
gpcore:
  core:
    envMap:
      NODE_IP: rabbitmq-build-external.$(NAMESPACE).svc.cluster.local
      NODE_NAME: spec.nodeName
      NODE_PORT: "5672"
    imageTag: 4.2.6.onprem.10
    imageTagArm: 4.2.6.onprem-arm64.1
influxdb:
  influxdb:
    envMap:
      INFLUXDB_ADMIN_PASSWORD: cGFzc3dvcmQ
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    image: influxdb
    imageTag: 1.7.10
mongodb:
  mongo:
    envMap:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_LITE_USERNAME: lite
    image: mongo
    imageTag: 4.0.4
  mongoInit:
    image: mongo
    imageTag: 4.0.4
nodechecker:
  nodechecker:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.4
    imageTagArm: 4.2.6.onprem-arm64.1
paymentmanager:
  paymentmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
rabbitmq:
  rabbitmq:
    envMap:
      RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ
      RABBITMQ_DEFAULT_USER: admin
    image: rabbitmq
    imageTag: 3.8.5
redis:
  redis:
    image: redis
    imageTag: 3.2-alpine
usermanager:
  usermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
webhook:
  webhook:
    envMap:
      APP_NAME: metadata.namespace
      HOST_IP: status.hostIP
      NODE_NAME: spec.nodeName
      REPLICA_IP: status.podIP
    imageTag: 4.2.6.onprem.9
    imageTagArm: 4.2.6.onprem-arm64.2
marketplace:
  marketplace:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: 4.2.6.onprem.5
    imageTagArm: 4.2.6.onprem-arm64.1
defaultbackend:
  defaultbackend:
    image: defaultbackend
    imageTag: 1.4
nginxIngress:
  nginxIngress:
    image: nginx/nginx-ingress
    imageTag: 3.1-alpine