activitymanager:
  activitymanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
alertmanager:
  alertmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
appscanner:
  appscanner:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.4
appworker:
  appworker:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: dev.lite.13
cloudmanager:
  cloudmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
clustermanager:
  clustermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.11
clustertemplatemanager:
  clustertemplatemanager:
    imageTag: dev.lite.3
configmanager:
  configmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.8
costmanager:
  costmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.4
deploymentmanager:
  deploymanager:
    envMap:
      NODE_NAME: spec.nodeName
      rabbitmq_user: admin
    imageTag: dev.lite.13
domainmanager:
  domainmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.6
esearch:
  esearch:
    envMap:
      discovery.type: single-node
    imageTag: 1.7.3
gateway:
  gateway:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
  gpkubeux:
    envMap:
      HOST: 0.0.0.0
    imageTag: dev.lite.14
    gpReleaseVersion: 4.2.6
gpcore:
  core:
    envMap:
      NODE_IP: rabbitmq-build-external.$(NAMESPACE).svc.cluster.local
      NODE_NAME: spec.nodeName
      NODE_PORT: "5672"
    imageTag: dev.lite.3
influxdb:
  influxdb:
    envMap:
      INFLUXDB_ADMIN_PASSWORD: cGFzc3dvcmQ
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    imageTag: 1.7.10
mongodb:
  mongo:
    envMap:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_LITE_USERNAME: lite
    imageTag: 4.0.4
  mongoInit:
    imageTag: 4.0.4
nodechecker:
  nodechecker:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
paymentmanager:
  paymentmanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
rabbitmq:
  rabbitmq:
    envMap:
      RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ
      RABBITMQ_DEFAULT_USER: admin
    imageTag: 3.8.5
redis:
  redis:
    imageTag: 3.2-alpine
usermanager:
  usermanager:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
webhook:
  webhook:
    envMap:
      APP_NAME: metadata.namespace
      HOST_IP: status.hostIP
      NODE_NAME: spec.nodeName
      REPLICA_IP: status.podIP
    imageTag: dev.lite.4
marketplace:
  marketplace:
    envMap:
      NODE_NAME: spec.nodeName
    imageTag: dev.lite.3
