apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: configmanager
    app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
    family: servicegroup
    name: configmanager
    released-by: gopaddle
    servicegroup: configmanager-ntkg8uov
    servicegroup-name: configmanager
  name: configmanager
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: configmanager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configmanager
        app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
        family: servicegroup
        name: configmanager
        released-by: gopaddle
        servicegroup: configmanager-ntkg8uov
        servicetype: gopaddle
      name: configmanager
    spec:
      affinity: {}
{{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - args:
        - |-
          #!/bin/bash
          apk add --no-cache openrc busybox-initscripts
          openrc
          touch /run/openrc/softlevel
          rc-service crond start
          cat <<EOF >/etc/periodic/15min/logcleanscript
          #!/bin/sh
          cd /var/log/gopaddle/
          rm -rf *.tar.gz
          tar -cvzf log.tar.gz *.log
          echo "" > configmanager.log
          EOF
          chmod a+x /etc/periodic/15min/logcleanscript
          echo "0 0 * * * /etc/periodic/15min/logcleanscript > /var/log/cron.log 2>&1" >> logclean.cron
          /usr/bin/crontab logclean.cron

          ./configmanager kube > /var/log/gopaddle/configmanager.log
          tail -f /var/log/gopaddle/configmanager.log
        command:
        - /bin/sh
        - -c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: {{ quote .Values.configmanager.configmanager.envMap.NODE_NAME }}
        - name: GP_RELEASE
          value: gp-4.2
        envFrom:
        - secretRef:
            name: configmanager-configmanager-envsecret-n8xui
{{- if eq (.Values.global.installer.arch | toString) "arm64" }}
        image: {{ template "gopaddle.registryUrl" . }}/configmanager:{{ .Values.configmanager.configmanager.imageTagArm }}
{{- else }}
        image: {{ template "gopaddle.registryUrl" . }}/configmanager:{{ .Values.configmanager.configmanager.imageTag }}
{{- end }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: configmanager
        ports:
        - containerPort: 8001
          name: 8001-tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 10m
            memory: 50M
        securityContext: {}
        volumeMounts:
        - mountPath: /app/config
          name: configmanager-configmanager-cmnt-atpo0
        - mountPath: /var/log/gopaddle/
          name: log
      imagePullSecrets:
{{- if .Values.global.airgapped.enabled }}
      - name: {{ .Values.global.airgapped.imageRegistryInfo.imageSecret }}
{{- else }}
      - name: gcr-json-key
{{- end }}
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: configmanager-configmanager-configmap-hxdat
        name: configmanager-configmanager-cmnt-atpo0
      - emptyDir: {}
        name: log
status: {}
