apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: costmanager
    app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
    family: servicegroup
    name: costmanager
    released-by: gopaddle
    servicegroup: costmanager-olfgicj6
    servicegroup-name: costmanager
  name: costmanager
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: costmanager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: costmanager
        app-id: appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
        family: servicegroup
        name: costmanager
        released-by: gopaddle
        servicegroup: costmanager-olfgicj6
        servicetype: gopaddle
      name: costmanager
    spec:
      affinity: {}
{{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - args:
        - |-
          #!/bin/bash
          apk add --no-cache openrc busybox-initscripts
          openrc
          touch /run/openrc/softlevel
          rc-service crond start
          cat <<EOF >/etc/periodic/15min/logcleanscript
          #!/bin/sh
          cd /var/log/gopaddle/
          rm -rf *.tar.gz
          tar -cvzf log.tar.gz *.log
          echo "" > costmanager.log
          EOF
          chmod a+x /etc/periodic/15min/logcleanscript
          echo "0 0 * * * /etc/periodic/15min/logcleanscript > /var/log/cron.log 2>&1" >> logclean.cron
          /usr/bin/crontab logclean.cron

          ./costmanager kube > /var/log/gopaddle/costmanager.log
          tail -f /var/log/gopaddle/costmanager.log
        command:
        - /bin/sh
        - -c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: {{ quote .Values.costmanager.costmanager.envMap.NODE_NAME }}
        - name: GP_RELEASE
          value: gp-4.2
        envFrom:
        - secretRef:
            name: costmanager-costmanager-envsecret-nq4hj
{{- if eq (.Values.global.installer.arch | toString) "arm64" }}
        image: {{ template "gopaddle.registryUrl" . }}/costmanager:{{ .Values.costmanager.costmanager.imageTagArm }}
{{- else }}
        image: {{ template "gopaddle.registryUrl" . }}/costmanager:{{ .Values.costmanager.costmanager.imageTag }}
{{- end }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8011
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: costmanager
        ports:
        - containerPort: 8011
          name: 8011-tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8011
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 10m
            memory: 50M
        securityContext: {}
        volumeMounts:
        - mountPath: /app/config
          name: costmanager-costmanager-cmnt-gatch
        - mountPath: /var/log/gopaddle/
          name: log
      imagePullSecrets:
{{- if .Values.global.airgapped.enabled }}
      - name: {{ .Values.global.airgapped.imageRegistryInfo.imageSecret }}
{{- else }}
      - name: gcr-json-key
{{- end }}
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: costmanager-costmanager-configmap-q1g1s
        name: costmanager-costmanager-cmnt-gatch
      - emptyDir: {}
        name: log
status: {}
