{{- if eq (.Values.global.installer.edition | toString) "Lite" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: emailer-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "* 19 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - |-
              #!/bin/bash
              ARCH=`uname -m` && \
                if [ "$ARCH" == "x86_64" ]; then \
                  cp ./kubeaudit.amd64 ./kubeaudit; \
                else \
                  echo "unknown arch" && \
                  cp ./kubeaudit.arm64 ./kubeaudit; \
                fi
              chmod +x ./kubeaudit ./emailservice ./runAudit.sh
              sh -x ./runAudit.sh
            command:
            - /bin/sh
            - -c
            env:
            - name: NODE_IP
              value: {{ template "gopaddle.baseServerUI" . }}
            - name: GP_RELEASE
              value: {{ quote .Chart.AppVersion }}
{{- if eq (.Values.global.installer.arch | toString) "arm64" }}
            image: {{ template "gopaddle.registryUrl" . }}/emailer:{{ .Values.emailer.emailer.imageTagArm }}
{{- else }}
            image: {{ template "gopaddle.registryUrl" . }}/emailer:{{ .Values.emailer.emailer.imageTag }}
{{- end }}
            imagePullPolicy: IfNotPresent
            name: emailer
          restartPolicy: OnFailure
          imagePullSecrets:
{{- if .Values.global.airgapped.enabled }}
          - name: {{ .Values.global.airgapped.imageRegistryInfo.imageSecret }}
{{- else }}
          - name: gcr-json-key
{{- end }}
{{- end }}