{{- if ne (.Values.global.routingType | toString) "NodePortWithOutIngress" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: default-http-backend
    released-by: gopaddle
  name: default-http-backend
  # namespace: default
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: default-http-backend
      released-by: gopaddle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: default-http-backend
        released-by: gopaddle
    spec:
      containers:
{{- if eq (.Values.global.installer.arch | toString) "arm64" }}
      - image: {{ template "gopaddle.googleContainer.registryUrl" . }}/{{ .Values.defaultbackend.defaultbackend.imageArm }}:{{ .Values.defaultbackend.defaultbackend.imageTag }}
{{- else }}
      - image: {{ template "gopaddle.googleContainer.registryUrl" . }}/{{ .Values.defaultbackend.defaultbackend.image }}:{{ .Values.defaultbackend.defaultbackend.imageTag }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: default-http-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 70m
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 50Mi
      terminationGracePeriodSeconds: 60
{{- if .Values.global.airgapped.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.airgapped.imageRegistryInfo.imageSecret }}
{{- end }}
status: {}
{{- end }}