apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: marketplace
    app-id: appsa666871dcdb46c48d7c939cc17107348e44b
    family: servicegroup
    name: marketplace
    released-by: gopaddle
    servicegroup: marketplace-q5j701mv
    servicegroup-name: marketplace
  name: marketplace
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: marketplace
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marketplace
        app-id: appsa666871dcdb46c48d7c939cc17107348e44b
        family: servicegroup
        name: marketplace
        released-by: gopaddle
        servicegroup: marketplace-q5j701mv
        servicetype: gopaddle
      name: marketplace
    spec:
      affinity: {}
{{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - args:
        - |-
          #!/bin/bash
          apk add --no-cache openrc busybox-initscripts
          openrc
          touch /run/openrc/softlevel
          rc-service crond start
          cat <<EOF >/etc/periodic/15min/logcleanscript
          #!/bin/sh
          cd /var/log/gopaddle/
          rm -rf *.tar.gz
          tar -cvzf log.tar.gz *.log
          echo "" > marketplace.log
          EOF
          chmod a+x /etc/periodic/15min/logcleanscript
          echo "0 0 * * * /etc/periodic/15min/logcleanscript > /var/log/cron.log 2>&1" >> logclean.cron
          /usr/bin/crontab logclean.cron

          chmod +x helm
          mv helm /usr/local/bin
          # echo "----------- start conatainer ------------"
          ./marketplace kube > /var/log/gopaddle/marketplace.log
          tail -f /var/log/gopaddle/marketplace.log
        command:
        - /bin/sh
        - -c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: {{ quote .Values.marketplace.marketplace.envMap.NODE_NAME }}
        - name: GP_RELEASE
          value: gp-4.2
        envFrom:
        - secretRef:
            name: marketplace-marketplace-envsecret-rmadj
{{- if eq (.Values.global.installer.arch | toString) "arm64" }}
        image: {{ template "gopaddle.registryUrl" . }}/marketplace:{{ .Values.marketplace.marketplace.imageTagArm }}
{{- else }}
        image: {{ template "gopaddle.registryUrl" . }}/marketplace:{{ .Values.marketplace.marketplace.imageTag }}
{{- end }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8023
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: marketplace
        ports:
        - containerPort: 8023
          name: 8023-tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /api/status
            port: 8023
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 100m
            memory: 200M
        securityContext: {}
        volumeMounts:
        - mountPath: /app/config
          name: marketplace-marketplace-cmnt-xeiho
        - mountPath: /var/log/gopaddle/
          name: log
      imagePullSecrets:
{{- if .Values.global.airgapped.enabled }}
      - name: {{ .Values.global.airgapped.imageRegistryInfo.imageSecret }}
{{- else }}
      - name: gcr-json-key
{{- end }}
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: marketplace-marketplace-configmap-7dszg
        name: marketplace-marketplace-cmnt-xeiho
      - emptyDir: {}
        name: log
status: {}
