name: CI-pullrequest

on:
  pull_request:
    branches:
      - main-source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout into branch
        run: git checkout -b staging-pr-workflow
        
      - name: Fetch main-source
        run: git fetch origin main-source
        
      - name: Rebase to main-source
        run: git rebase origin/main-source

      - name: Pull scripts
        run: sudo make pull-scripts
      
      - name: Validate 
        run: sudo make validate
